config/routes.rb
Rails.application.routes.draw do
	root to: 'city_weathers#index'
  resources :city_weathers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city_weather.rb
class CityWeather < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/city_weathers_controller.rb
class CityWeathersController < ApplicationController
  require 'json'
  before_action :set_city_weather, only: [:show, :edit, :update, :destroy]

  # GET /city_weathers
  # GET /city_weathers.json
  def index
    # Get the CityWeather model
    @city_weathers = CityWeather.all
    @days_of_week = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat']

    # Get the JSON for each City
    @city_data = Array.new
    @city_weathers.each do |city_weather|
      # puts '-----------CITY WEATHER-------------'
      # puts city_weather.inspect
      # puts '------------------------------------'

      # Make sure the weather_id exists before we move on
      unless city_weather['weather_id'].nil?
        weather_data = JSON.parse(helpers.get_weather(city_weather['weather_id'],'id'))
        this_city = {
          'record' => city_weather, 
          'weather_data' => weather_data
        }
        @city_data << this_city
      end
    end
  end

  # GET /city_weathers/1
  # GET /city_weathers/1.json
  def show
  end

  # GET /city_weathers/new
  def new
    @city_weather = CityWeather.new
  end

  # GET /city_weathers/1/edit
  def edit
  end

  # POST /city_weathers
  # POST /city_weathers.json
  def create
    # puts "=============CITY WEATHER PARAMS============="
    # puts city_weather_params
    # puts "============================================="
    if city_weather_params['cityName'].empty?
      data = city_weather_params['zipCode']
      param = "zip"
    else
      data = city_weather_params['cityName']
      param = "q"
    end
    weather_data = JSON.parse(helpers.get_weather(data,param))

    puts "=============Code============="
    puts weather_data
    puts weather_data.instance_of? Hash
    # puts weather_data['cod']
    puts "============================================="

    unless weather_data['cod'] == '200'
      redirect_to '/city_weathers/new', alert: "Bogus City!!"
    else
      # puts "=============CREATE RESPONSE============="
      # puts city_weather_params
      # puts "========================================="
      # weather_id
      @city_weather = CityWeather.new(city_weather_params.merge(:weather_id => weather_data['city']['id']))

      # respond_to do |format|
        if @city_weather.save
          redirect_to '/', notices: "Added!"
        else
          format.html { render :new }
          format.json { render json: @city_weather.errors, status: :unprocessable_entity }
        end
      # end
    end
  end

  # PATCH/PUT /city_weathers/1
  # PATCH/PUT /city_weathers/1.json
  def update
    respond_to do |format|
      if @city_weather.update(city_weather_params)
        format.html { redirect_to @city_weather, notice: 'City weather was successfully updated.' }
        format.json { render :show, status: :ok, location: @city_weather }
      else
        format.html { render :edit }
        format.json { render json: @city_weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /city_weathers/1
  # DELETE /city_weathers/1.json
  def destroy
    @city_weather.destroy
    respond_to do |format|
      format.html { redirect_to city_weathers_url, notice: 'City weather was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city_weather
      @city_weather = CityWeather.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_weather_params
      params.require(:city_weather).permit(:cityName, :zipCode, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_weathers_helper.rb
# A helper module to put all the http requests in one place
module CityWeathersHelper
  def get_weather(city, query_type)
  	# Include http service,json,cgi (part of core Rails)
    require 'net/http'
    require 'json'
    require 'cgi'
  	weather_api_key = Rails.application.config_for(:weather)['api_key']
  	# Set up URL's
  	puts '--------CITY--------'
  	puts city
  	safe_city = CGI.escape(city.to_s)
    base_url = url = "https://api.openweathermap.org/data/2.5/forecast/daily?appid=#{weather_api_key}&units=imperial&"
    full_url = "#{base_url}#{query_type}=#{safe_city}"
    # Print/test out the finished URL
  	puts '============FULL URL============='
  	puts full_url
  	puts '=================================='

  	# Convert the url string to make Rails happy
    uri = URI(full_url)
    response = Net::HTTP.get(uri)
    return response
  end
end

app/views/city_weathers/_form.html.erb
<%= form_with(model: city_weather, local: true) do |form| %>
  <% if city_weather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city_weather.errors.count, "error") %> prohibited this city_weather from being saved:</h2>

      <ul>
      <% city_weather.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cityName %>
    <%= form.text_field :cityName, id: :city_weather_cityName %>
  </div>

  <div class="field">
    <%= form.label :zipCode %>
    <%= form.number_field :zipCode, id: :city_weather_zipCode, :readonly => true %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc, id: :city_weather_desc %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/city_weathers/edit.html.erb
<h1>Editing City Weather</h1>

<%= render 'form', city_weather: @city_weather %>

<%= link_to 'Show', @city_weather %> |
<%= link_to 'Back', city_weathers_path %>

app/views/city_weathers/index.html.erb
<%= javascript_include_tag "https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js" %>

<p id="notice"><%= notice %></p>

<h1>City Weather Tiler</h1>

  <% if @city_weathers.length == 0 %>
    <h2>You need to add some cities!</h2>
  <% else %>
    <div class="filter col-sm-12">
      <button class="warm-ones btn btn-success">Just the warm ones</button>
      <button class="all btn btn-danger">All</button>
    </div>  
    <div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
      <% @city_data.each do |city| %>
          <% main = city['weather_data']['list'][0]['weather'][0]['main'] %>
          <% current = city['weather_data']['list'][0]['temp']['max'] %>
          <% main_icon = city['weather_data']['list'][0]['weather'][0]['icon'] %>
        </tr>
      

      <% 
        if current > 70
          iso_class = "warm" 
        end 
      %>
      <div class="box <%= iso_class %>">
          <div class="top-box col-sm-12">
          <!-- Upper Left Info -->
          <div class="col-sm-6 current">
            <%= main %>
          </div>
          <!-- Upper Right Info -->
          <div class="col-sm-6">
            <div class="delete-city">
              <%= link_to 'x', city['record'], method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
            <div class="col-sm-12 text-right">
              <%= city['weather_data']['city']['name'] %>
            </div>

            <div class="col-sm-12 text-right">
              <%= city['weather_data']['city']['country'] %>
            </div>
          </div>
        </div>

        <div class="main-icon">
          <span class="current-temp"><%=current.round %>&deg;</span>
          <span class="current-icon"><img src="http://openweathermap.org/img/w/<%=main_icon%>.png" /></span>
        </div>

        <div class="col-sm-12 city-days">
          <% for i in 1..5 do %>
            <% day_of_week = @days_of_week[Time.at(city['weather_data']['list'][i]['dt']).wday] %>
            <% temp = city['weather_data']['list'][i]['temp']['max'] %>

            <div class="date-temp day<%=i%>">
              <div class="day-of-week"><%= day_of_week %></div>
              <div class="doy-icon">
                <img src="http://openweathermap.org/img/w/<%= city['weather_data']['list'][i]['weather'][0]['icon'] %>.png" />
              </div>
              <div class="doy-temp"><%= temp.to_i %>&deg;</div>
            </div>

          <% end %>

          <!-- <%= link_to 'Show', city['record'] %> -->
          <div class="desc">
            <%= truncate city['record']['desc'], :length => 30, :separator => /\w/ %>
          </div>          
          <div class="edit col-sm-12">
            <%= link_to 'Edit', edit_city_weather_path(city['record']) %>
          </div>

        </div>
      </div>      


      <% end %>
    </div>
<% end %>

app/views/city_weathers/new.html.erb
<h1>New City Weather</h1>

<%= render 'form', city_weather: @city_weather %>

<%= link_to 'Back', city_weathers_path %>

app/views/city_weathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cityname:</strong>
  <%= @city_weather.cityName %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @city_weather.zipCode %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @city_weather.desc %>
</p>

<%= link_to 'Edit', edit_city_weather_path(@city_weather) %> |
<%= link_to 'Back', city_weathers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherTiler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/city_weathers.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WeatherTiler" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">WeatherTiler</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Add a new city tile!', new_city_weather_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>